"""DocMind WebSocket chat handler with citation tracking, LLM streaming,
and persistent chat history.

Provides a real-time Q&A interface where users can ask questions about their
documents and receive answers with inline citation references. Conversations
are persisted to the Database (chat_sessions + chat_messages tables) so they
survive page refreshes and can be browsed via the REST API.

When an LLM provider is configured (DOCMIND_LLM_PROVIDER), answers are
generated by the LLM from retrieved document context using RAG. When no LLM
is configured, a simple extractive answer is built from search snippets.

Protocol:
    Server -> Client (on connect):
        {"type": "connected", "message": "...", "session_id": "<uuid>",
         "title": "..."}
    Client -> Server: {"type": "question", "text": "What is the pipeline design?"}
    Server -> Client: {"type": "citation:added", "doc_id": 42, "title": "...", "snippet": "..."}
    Server -> Client: {"type": "answer:chunk", "text": "The pipeline..."}
    Server -> Client: {"type": "answer:done", "citations": [...], "session_id": "<uuid>"}
"""

from __future__ import annotations

import json
import logging
from typing import Any, Optional

from fastapi import WebSocket, WebSocketDisconnect

from ..core.config import config
from ..core.db_sqlite import Database
from ..core.llm_client import LLMClient
from ..core.search import SearchEngine, HybridSearchEngine
from ..core.search_backend import SearchBackend, create_backend

logger = logging.getLogger(__name__)

# ── Conversation context ─────────────────────────────────────────


class ConversationContext:
    """Holds per-connection state for a chat session."""

    def __init__(
        self,
        websocket: WebSocket,
        search_engine: SearchEngine,
        llm_client: Optional[LLMClient] = None,
        *,
        db: Optional[Database] = None,
        session_id: Optional[str] = None,
    ) -> None:
        self.websocket = websocket
        self.search_engine = search_engine
        # Guarantee a client — fallback mode if none provided
        self.llm_client: LLMClient = llm_client or LLMClient(config.llm)
        self.citation_count: int = 0
        self.collected_citations: list[dict[str, Any]] = []
        # Persistence
        self.db: Optional[Database] = db
        self.session_id: Optional[str] = session_id
        self.session_title: str = "New Chat"

    def add_citation(
        self, doc_id: int, title: str, snippet: str, confidence: str
    ) -> int:
        """Record a citation and return its reference number."""
        self.citation_count += 1
        ref = self.citation_count
        citation = {
            "ref": ref,
            "doc_id": doc_id,
            "title": title,
            "snippet": snippet,
            "confidence": confidence,
        }
        self.collected_citations.append(citation)
        return ref


# ── WebSocket handler ────────────────────────────────────────────


async def handle_chat(
    websocket: WebSocket,
    *,
    search_db_path: str = "data/docmind_fts.db",
    llm_client: Optional[LLMClient] = None,
    db: Optional[Database] = None,
) -> None:
    """Handle a WebSocket chat connection for real-time document Q&A.

    Lifecycle:
    1. Accept connection, resolve/create session, send connected with session_id
    2. Loop: receive question -> search -> stream answer with citations
       - Persist each user question and assistant answer to the DB
    3. On disconnect: clean up

    Args:
        websocket: The WebSocket connection. A ``session_id`` query parameter
            may be supplied on the WebSocket URL; if absent or unknown, a new
            session is created.
        search_db_path: Path to the SQLite FTS database.
        llm_client: Optional LLMClient for LLM-powered answers. If None,
            creates one from global config (which may be unconfigured,
            triggering extractive fallback).
        db: Optional Database for persisting chat sessions and messages.
            If None, chat runs without persistence (back-compat behavior).
    """
    await websocket.accept()

    # Initialize search backend
    backend = create_backend("sqlite", db_path=search_db_path)
    search_engine = SearchEngine(backend=backend)

    # Initialize LLM client — use provided one or create from config
    client = llm_client or LLMClient(config.llm)

    # Resolve session_id: prefer URL query param, fall back to None
    session_id: Optional[str] = None
    try:
        qp = websocket.query_params
        session_id = qp.get("session_id") or qp.get("session")
    except Exception:
        session_id = None

    # If a session_id was provided, verify it exists; otherwise create one
    session_title = "New Chat"
    if db is not None:
        if session_id:
            existing = await db.get_chat_session(session_id)
            if existing is None:
                # Unknown id -> create a fresh session with that id
                try:
                    created = await db.create_chat_session(session_id=session_id)
                    session_title = created.get("title", "New Chat")
                except Exception:
                    logger.exception("Failed to create chat session %s", session_id)
                    session_id = None
            else:
                session_title = existing.get("title", "New Chat")
        if not session_id:
            try:
                created = await db.create_chat_session()
                session_id = created["id"]
                session_title = created.get("title", "New Chat")
            except Exception:
                logger.exception("Failed to create chat session")
                session_id = None
    else:
        # No DB: ephemeral session id only (not persisted)
        if not session_id:
            import uuid as _uuid

            session_id = str(_uuid.uuid4())

    ctx = ConversationContext(
        websocket,
        search_engine,
        client,
        db=db,
        session_id=session_id,
    )
    ctx.session_title = session_title

    await _send(
        ctx,
        {
            "type": "connected",
            "message": "DocMind chat ready. Ask questions about your documents.",
            "session_id": session_id or "",
            "title": session_title,
        },
    )

    # If we have a DB and an existing session, replay its history to the client
    if db is not None and session_id:
        try:
            history = await db.get_chat_history(session_id, limit=50)
            if history:
                await _send(
                    ctx,
                    {
                        "type": "history",
                        "session_id": session_id,
                        "messages": [
                            {
                                "role": m["role"],
                                "content": m["content"],
                                "citations": m.get("citations", []),
                            }
                            for m in history
                        ],
                    },
                )
        except Exception:
            logger.exception("Failed to replay chat history for %s", session_id)

    try:
        while True:
            raw = await websocket.receive_text()
            try:
                message = json.loads(raw)
            except json.JSONDecodeError:
                await _send(ctx, {"type": "error", "message": "Invalid JSON"})
                continue

            msg_type = message.get("type", "")

            if msg_type == "question":
                await _handle_question(ctx, message.get("text", ""))
            elif msg_type == "ping":
                await _send(ctx, {"type": "pong"})
            else:
                await _send(
                    ctx,
                    {
                        "type": "error",
                        "message": f"Unknown message type: {msg_type}",
                    },
                )

    except WebSocketDisconnect:
        logger.info("WebSocket client disconnected")
    except Exception:
        logger.exception("WebSocket handler error")
    finally:
        backend.close()
        # Close LLM client if we created it
        if llm_client is None and client:
            try:
                await client.close()
            except Exception:
                pass


async def _handle_question(ctx: ConversationContext, text: str) -> None:
    """Process a question: search, cite, stream an LLM answer, persist messages."""
    if not text or not text.strip():
        await _send(ctx, {"type": "error", "message": "Empty question"})
        return

    logger.info("Chat question: %s", text[:100])

    # Persist the user question (and set session title from first question)
    if ctx.db is not None and ctx.session_id:
        try:
            await ctx.db.save_chat_message(
                ctx.session_id, "user", text, citations=None
            )
            # Auto-title from first user message (first 50 chars)
            existing = await ctx.db.get_chat_session(ctx.session_id)
            if existing and (existing.get("title") in (None, "", "New Chat")):
                title = text.strip()[:50]
                await ctx.db.update_chat_session_title(ctx.session_id, title)
                ctx.session_title = title
        except Exception:
            logger.exception("Failed to persist user question")

    # Search for relevant documents
    # If the search engine supports chunk-level search, use it for
    # more precise context (fewer tokens, specific passages).
    try:
        if isinstance(ctx.search_engine, HybridSearchEngine):
            # Chunk-level hybrid search — returns individual chunks
            chunk_results = await ctx.search_engine.search_chunks(
                text, top_k=5
            )
            if chunk_results:
                results = _convert_chunk_results(chunk_results)
            else:
                results = []
        else:
            results = ctx.search_engine.search(
                text,
                top_k=5,
                include_citations=True,
            )
    except Exception as e:
        logger.exception("Search failed during chat")
        await _send(ctx, {"type": "error", "message": f"Search failed: {e}"})
        return

    if not results:
        no_results_text = (
            "I couldn't find any relevant documents for your question."
        )
        await _send(
            ctx,
            {
                "type": "answer:done",
                "text": no_results_text,
                "citations": [],
                "session_id": ctx.session_id or "",
            },
        )
        # Persist the assistant answer even when no results
        if ctx.db is not None and ctx.session_id:
            try:
                await ctx.db.save_chat_message(
                    ctx.session_id, "assistant", no_results_text, citations=[]
                )
            except Exception:
                logger.exception("Failed to persist no-results answer")
        return

    # Reset citations for this question
    ctx.citation_count = 0
    ctx.collected_citations = []

    # Send citation events for each source
    for result in results:
        citation = result.get("citation", {})
        ref = ctx.add_citation(
            doc_id=result["doc_id"],
            title=result.get("title", "Untitled"),
            snippet=result.get("snippet", ""),
            confidence=citation.get("confidence", "low"),
        )

        citation_event: dict[str, Any] = {
            "type": "citation:added",
            "ref": ref,
            "doc_id": result["doc_id"],
            "title": result.get("title", ""),
            "snippet": result.get("snippet", ""),
            "confidence": citation.get("confidence", "low"),
        }
        # Include chunk-level citation metadata when available
        if "chunk_index" in citation:
            citation_event["chunk_index"] = citation["chunk_index"]
        if "chunk_id" in citation:
            citation_event["chunk_id"] = citation["chunk_id"]

        await _send(ctx, citation_event)

    # Stream the answer using LLM (with extractive fallback)
    full_answer = ""
    async for chunk in ctx.llm_client.generate_stream(text, results):
        full_answer += chunk
        await _send(ctx, {"type": "answer:chunk", "text": chunk})

    # Persist the assistant answer (with citations)
    if ctx.db is not None and ctx.session_id:
        try:
            await ctx.db.save_chat_message(
                ctx.session_id,
                "assistant",
                full_answer,
                citations=ctx.collected_citations,
            )
        except Exception:
            logger.exception("Failed to persist assistant answer")

    # Send final answer with full citation list
    await _send(
        ctx,
        {
            "type": "answer:done",
            "text": full_answer,
            "citations": ctx.collected_citations,
            "session_id": ctx.session_id or "",
        },
    )


async def _send(ctx: ConversationContext, message: dict[str, Any]) -> None:
    """Send a JSON message over the WebSocket."""
    try:
        await ctx.websocket.send_text(json.dumps(message, default=str))
    except Exception:
        pass  # Connection may be closed


def _convert_chunk_results(
    chunk_results: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Convert chunk-level search results to the format expected by chat.

    Each chunk result is converted to a dict with keys compatible with
    the rest of _handle_question: doc_id, title, snippet, body, citation.
    The snippet is the chunk content (truncated), and the citation
    references the specific chunk, not just the document.
    """
    output: list[dict[str, Any]] = []
    for chunk in chunk_results:
        content = chunk.get("chunk_content", "")
        output.append({
            "doc_id": chunk.get("doc_id", 0),
            "title": chunk.get("title", "Untitled"),
            "snippet": content[:500],
            "body": content,
            "rank": chunk.get("rank", 0.0),
            "citation": {
                "confidence": "medium",
                "chunk_index": chunk.get("chunk_index", 0),
                "chunk_id": chunk.get("chunk_id", 0),
                "start_char": chunk.get("start_char", 0),
                "end_char": chunk.get("end_char", 0),
            },
        })
    return output
