"""DocMind WebSocket chat handler with citation tracking and LLM streaming.

Provides a real-time Q&A interface where users can ask questions about their
documents and receive answers with inline citation references.

When an LLM provider is configured (DOCMIND_LLM_PROVIDER), answers are
generated by the LLM from retrieved document context using RAG. When no LLM
is configured, a simple extractive answer is built from search snippets.

Protocol:
    Client → Server: {"type": "question", "text": "What is the pipeline design?"}
    Server → Client: {"type": "citation:added", "doc_id": 42, "title": "...", "snippet": "..."}
    Server → Client: {"type": "answer:chunk", "text": "The pipeline..."}
    Server → Client: {"type": "answer:done", "citations": [...]}
"""

from __future__ import annotations

import json
import logging
from typing import Any, Optional

from fastapi import WebSocket, WebSocketDisconnect

from ..core.config import config
from ..core.llm_client import LLMClient
from ..core.search import SearchEngine
from ..core.search_backend import SearchBackend, create_backend

logger = logging.getLogger(__name__)

# ── Conversation context ─────────────────────────────────────────


class ConversationContext:
    """Holds per-connection state for a chat session."""

    def __init__(
        self,
        websocket: WebSocket,
        search_engine: SearchEngine,
        llm_client: Optional[LLMClient] = None,
    ):
        self.websocket = websocket
        self.search_engine = search_engine
        # Guarantee a client — fallback mode if none provided
        self.llm_client: LLMClient = llm_client or LLMClient(config.llm)
        self.citation_count: int = 0
        self.collected_citations: list[dict[str, Any]] = []

    def add_citation(self, doc_id: int, title: str, snippet: str, confidence: str) -> int:
        """Record a citation and return its reference number."""
        self.citation_count += 1
        ref = self.citation_count
        citation = {
            "ref": ref,
            "doc_id": doc_id,
            "title": title,
            "snippet": snippet,
            "confidence": confidence,
        }
        self.collected_citations.append(citation)
        return ref


# ── WebSocket handler ────────────────────────────────────────────


async def handle_chat(
    websocket: WebSocket,
    *,
    search_db_path: str = "data/docmind_fts.db",
    llm_client: Optional[LLMClient] = None,
) -> None:
    """Handle a WebSocket chat connection for real-time document Q&A.

    Lifecycle:
    1. Accept connection, send welcome
    2. Loop: receive question → search → stream answer with citations
    3. On disconnect: clean up

    Args:
        websocket: The WebSocket connection.
        search_db_path: Path to the SQLite FTS database.
        llm_client: Optional LLMClient for LLM-powered answers. If None,
            creates one from global config (which may be unconfigured,
            triggering extractive fallback).
    """
    await websocket.accept()

    # Initialize search backend
    backend = create_backend("sqlite", db_path=search_db_path)
    search_engine = SearchEngine(backend=backend)

    # Initialize LLM client — use provided one or create from config
    client = llm_client or LLMClient(config.llm)

    ctx = ConversationContext(websocket, search_engine, client)

    await _send(ctx, {
        "type": "connected",
        "message": "DocMind chat ready. Ask questions about your documents.",
    })

    try:
        while True:
            raw = await websocket.receive_text()
            try:
                message = json.loads(raw)
            except json.JSONDecodeError:
                await _send(ctx, {
                    "type": "error",
                    "message": "Invalid JSON",
                })
                continue

            msg_type = message.get("type", "")

            if msg_type == "question":
                await _handle_question(ctx, message.get("text", ""))
            elif msg_type == "ping":
                await _send(ctx, {"type": "pong"})
            else:
                await _send(ctx, {
                    "type": "error",
                    "message": f"Unknown message type: {msg_type}",
                })

    except WebSocketDisconnect:
        logger.info("WebSocket client disconnected")
    except Exception:
        logger.exception("WebSocket handler error")
    finally:
        backend.close()
        # Close LLM client if we created it
        if llm_client is None and client:
            try:
                await client.close()
            except Exception:
                pass


async def _handle_question(ctx: ConversationContext, text: str) -> None:
    """Process a question: search, cite, and stream an LLM answer."""
    if not text or not text.strip():
        await _send(ctx, {"type": "error", "message": "Empty question"})
        return

    logger.info("Chat question: %s", text[:100])

    # Search for relevant documents
    try:
        results = ctx.search_engine.search(
            text,
            top_k=5,
            include_citations=True,
        )
    except Exception as e:
        logger.exception("Search failed during chat")
        await _send(ctx, {"type": "error", "message": f"Search failed: {e}"})
        return

    if not results:
        await _send(ctx, {
            "type": "answer:done",
            "text": "I couldn't find any relevant documents for your question.",
            "citations": [],
        })
        return

    # Reset citations for this question
    ctx.citation_count = 0
    ctx.collected_citations = []

    # Send citation events for each source
    for result in results:
        citation = result.get("citation", {})
        ref = ctx.add_citation(
            doc_id=result["doc_id"],
            title=result.get("title", "Untitled"),
            snippet=result.get("snippet", ""),
            confidence=citation.get("confidence", "low"),
        )

        await _send(ctx, {
            "type": "citation:added",
            "ref": ref,
            "doc_id": result["doc_id"],
            "title": result.get("title", ""),
            "snippet": result.get("snippet", ""),
            "confidence": citation.get("confidence", "low"),
        })

    # Stream the answer using LLM (with extractive fallback)
    full_answer = ""
    async for chunk in ctx.llm_client.generate_stream(text, results):
        full_answer += chunk
        await _send(ctx, {"type": "answer:chunk", "text": chunk})

    # Send final answer with full citation list
    await _send(ctx, {
        "type": "answer:done",
        "text": full_answer,
        "citations": ctx.collected_citations,
    })


async def _send(ctx: ConversationContext, message: dict[str, Any]) -> None:
    """Send a JSON message over the WebSocket."""
    try:
        await ctx.websocket.send_text(json.dumps(message, default=str))
    except Exception:
        pass  # Connection may be closed
